// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wejusuxizsmcwsiulpbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlanVzdXhpenNtY3dzaXVscGJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDY4MTcsImV4cCI6MjA3MDc4MjgxN30.NLbKXx79Sv-kHHD5d8NG0M6d-yo0-jiQBzdejt4ZlYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});